### ISSUE TITLE
How to ensure that correct time is uploaded to DS3231

### ISSUE THREAD

**Issue by mcsysmcsys** [Erriez/ErriezDS3231#3]
When loading the sketch SetBuildTime, time is updated, but with an offset of about 11 seconds. 
So the time is not accurate, but 11 seconds later.

How to deal with this?

**Comment by Erriez** [comment]
Hi @mcsysmcsys, Thanks for using my library.

The sketch [ErriezDS3231SetBuildDateTime](https://github.com/Erriez/ErriezDS3231/blob/master/examples/ErriezDS3231SetBuildDateTime/ErriezDS3231SetBuildDateTime.ino) uses the date/time macro's `__DATE__` and `__TIME__` at build time. There is a delay between building the sketch and running the sketch which updates the new RTC time. In your case 11 seconds.

If you want to program a more accurate time, you can look at sketch [ErriezDS3231Terminal](https://github.com/Erriez/ErriezDS3231/tree/master/examples/ErriezDS3231Terminal) which includes a Python script to sync the time from the computer.

Does this answer your question?

**Comment by mcsysmcsys** [comment]
Thank you for your answer.  Sorry, but I am an NOOB in this field. Appreciate your help.

How would the terminal library help with setting an accurate time?  
btw I am a bit puzzled, what is the point of having a fairly accurate clock like ds3231, but with impossibility to set it accurately...

What would be great is a sketch that sets the time using pc time(which is accurate NTP), but also checks if there is an offset. Then setting again compensating for that.
Hope that makes sense ;)

**Comment by Erriez** [comment]
The design depends on the accuracy requirements:
- Sketch [ErriezDS3231SetBuildDateTime](https://github.com/Erriez/ErriezDS3231/blob/master/examples/ErriezDS3231SetBuildDateTime/ErriezDS3231SetBuildDateTime.ino) contains a delay of ~10 seconds.
- You can create a sketch which contains a date/time one minute earlier. Hold down reset button and release it exactly at the time you want to program the date/time as configured in the sketch. The sketch should prevent re-programming the date/time, for example by checking a GPIO pin. Setting the time manually can be 100..500ms accurate.
- The [ErriezDS3231Terminal.py script](https://github.com/Erriez/ErriezDS3231/blob/master/examples/ErriezDS3231Terminal/ErriezDS3231Terminal.py) uses the computer time to program the RTC date/time over serial. This has accuracy <100ms.
- NTP has accuracy in milliseconds, for example when using an ESP8266 or ESP32.
- Writing a new date/time over I2C to the RTC also takes time at a 100kHz clock and can to be compensated with a fixed offset.

**Comment by Erriez** [comment]
Closing issue as syncing accurate RTC time is beyond the scope of this library.
