### ISSUE TITLE
How change SDA and SCL pin?

### ISSUE THREAD

**Issue by mariocondesantos** [Erriez/ErriezDS3231#4]
Hi,

I can change SDA and SCL pin in code?
I use ESP32 and have a conflit with LCD ST7796...
tks

**Comment by Erriez** [comment]
Hi @mariocondesantos,

Thanks for using my library. You can change the ESP32 I2C pins in your sketch:

```c++
Wire.begin(SDA_PIN, SCL_PIN);
```

**Comment by mariocondesantos** [comment]
But change general I2C pinout in my Esp32 and my display stops working...
My display use I2C also...
![image](https://user-images.githubusercontent.com/73067209/159155421-ab8d1301-02a3-4ac4-a3bf-2913301e2186.jpg)
![image](https://user-images.githubusercontent.com/73067209/159155463-63980947-ebfb-4d77-985d-2e1f771d4024.jpg)

**Comment by Erriez** [comment]
Are the DS3231 examples up and running on your ESP32 board without using other devices? Make sure the DS3231 I2C pins uses different pins as they cannot be shared with a non I2C devices. Multiple I2C devices can be connected to the same I2C bus when each device has a unique address.

**Comment by Erriez** [comment]
Closing issue as ESP32 I2C pin configuration is beyond the scope of this DS3231 library.
