### ISSUE TITLE
aggregate 'tm dt' has incomplete type and cannot be defined      struct tm dt;

### ISSUE THREAD

**Issue by whoim2** [Erriez/ErriezDS3231#5]
`C:\Program Files (x86)\Arduino\libraries\ErriezDS3231\src\ErriezDS3231.cpp: In member function 'bool ErriezDS3231::getDateTime(uint8_t*, uint8_t*, uint8_t*, uint8_t*, uint8_t*, uint16_t*, uint8_t*)':
C:\Program Files (x86)\Arduino\libraries\ErriezDS3231\src\ErriezDS3231.cpp:398:15: error: aggregate 'tm dt' has incomplete type and cannot be defined
     struct tm dt;
`

**Comment by Erriez** [comment]
Which Arduino IDE are you using and which board is selected?

Can you select an UNO board in the Arduino 1.8.19 IDE and build any of the `Examples | Erriez DS3231 RTC`?
