### ISSUE TITLE
[QUESTION] How to check if the battery is dead or not?

### ISSUE THREAD

**Issue by zekageri** [Erriez/ErriezDS3231#6]

**Comment by Erriez** [comment]
The DS3231 does not provide an interface to read the battery status. The battery voltage can be measured with a multi-meter, or check the oscillator running state after power-on with `isRunning()` (set to false by default when battery is empty after power-cycle).

**Comment by zekageri** [comment]
Thank you for the answer. I appreciate your help. 

The oscillator flag always indicate the absence of the battery even if I force the bit on?

**Comment by Erriez** [comment]
Function `isRunning()` returns the value of register `STATUS` bit `OSF`. For details about the behavior of this flag, please refer to the datasheet [DS3231.pdf](https://raw.githubusercontent.com/Erriez/ErriezDS3231/master/extras/DS3231.pdf) Bit 7 OSF flag on page 14.

**Comment by zekageri** [comment]
Ohh I see. Thanks. So we must turn on the EOSC bit first to be able to use the osc flag.

**Comment by zekageri** [comment]
```
Bit 7: Oscillator Stop Flag (OSF). A logic 1 in this bit indi-
cates that the oscillator either is stopped or was stopped 
for some period and may be used to judge the validity of 
the timekeeping data. This bit is set to logic 1 any time 
that the oscillator stops. The following are examples of 
conditions that can cause the OSF bit to be set:
1) The first time power is applied.
2) The voltages present on both VCC and VBAT are insuf-
ficient to support oscillation.
3) The EOSC bit is turned off in battery-backed mode.
4) External influences on the crystal (i.e., noise, leakage, 
etc.).
This bit remains at logic 1 until written to logic 0.
```

The `isRunning()` method is a little bit confusing in this case. If the bit is 1 it indicates that it was stopped. So if `isRunning()` returns true the bit was false? 

Any method to enable the `EOSC` bit so it can be alway 1?

**Comment by zekageri** [comment]
Oh nevermind. I can see the clockEnable method does this. Thank you for your help. Great library!
